### ISSUE TITLE
请问ipk在哪儿啊？没找到

### ISSUE THREAD

**Issue by RCAPSN** [xmapst/GL-MT1300_Plugin#2]
多谢分享啊，Release里没啥啊，怎么下载ipk啊？谢谢

**Comment by xmapst** [comment]
[actions](https://github.com/xmapst/GL-MT1300_Plugin/actions)里面

**Comment by xmapst** [comment]
> 多谢分享啊，Release里没啥啊，怎么下载ipk啊？谢谢

[actions](https://github.com/xmapst/GL-MT1300_Plugin/actions)里面
