### ISSUE TITLE
提示passwall.lua无效

### ISSUE THREAD

**Issue by Broaden-your-horizon** [xmapst/GL-MT1300_Plugin#4]
/usr/lib/lua/luci/dispatcher.lua:1082: Invalid controller file found
The file '/usr/lib/lua/luci/controller/passwall.lua' contains an invalid module line.
Please verify whether the module name is set to 'luci.controller.passwall' - It must correspond to the file path!
stack traceback:
	[C]: in function 'assert'
	/usr/lib/lua/luci/dispatcher.lua:1082: in function 'createindex'
	/usr/lib/lua/luci/dispatcher.lua:1192: in function 'createtree'
	/usr/lib/lua/luci/dispatcher.lua:694: in function 'menu_json'
	/usr/lib/lua/luci/dispatcher.lua:795: in function 'dispatch'
	/usr/lib/lua/luci/dispatcher.lua:478: in function </usr/lib/lua/luci/dispatcher.lua:477>
提示passwall.lua无效 现在进不去luci界面了

**Comment by Broaden-your-horizon** [comment]
------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xmapst/GL-MT1300_Plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月13日(星期四) 上午9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xmapst/GL-MT1300_Plugin] 提示passwall.lua无效 (Issue #4)





   
@Broaden-your-horizon 安装的是哪天的构建版本
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Broaden-your-horizon** [comment]
------------------ 原始邮件 ------------------
发件人:                                                                                                                        "xmapst/GL-MT1300_Plugin"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年1月13日(星期四) 上午9:13
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [xmapst/GL-MT1300_Plugin] 提示passwall.lua无效 (Issue #4)





   
@Broaden-your-horizon 安装的是哪天的构建版本
 
—
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by Broaden-your-horizon** [comment]
> > 
> 
> @Broaden-你的-地平线安装的是哪天的构建版本

OpenWrt_packages_gl-mt1300_202201120355 昨天的构建版本

**Comment by xmapst** [comment]
> > > 
> > 
> > 
> > @Broaden-你的-地平线安装的是哪天的构建版本
> 
> OpenWrt_packages_gl-mt1300_202201120355 昨天的构建版本

检查一下以下安装包是否都已安装
```
opkg update
opkg install luci ttyd luci-app-ttyd luci-compat luci-lib-ipkg wget htop
```

**Comment by Broaden-your-horizon** [comment]
这些都 已安装，我重新安装 今天构建的发现 ipk包发现 
Upgrading netifd on root from 2021-01-09-753c351b-1 to 2021-01-09-753c351b-2...
bridge name     bridge id               STP enabled     interfaces
br-lan          7fff.9483c410a9b3       no              eth0.1
                                                        ra0
                                                        rax0
正在研究相关问题是否是我无法运行网络代理的原因

**Comment by Broaden-your-horizon** [comment]
找到问题原因了
