### ISSUE TITLE
似乎不支持大容量TF卡

### ISSUE THREAD

**Issue by CNszDiego** [xmapst/GL-MT1300_Plugin#6]
我刷了Lean的固件，雷克沙的64GB TF卡插上去没反应。我以为是没有装上TF卡的插件。运行
opkg install kmod-mmc kmod-sdhci报错，说已经打包在内了。
挂载点里也看不到TF卡的情况。

望高手指点。

**Comment by xmapst** [comment]
> 

这得去lean那边提问看看, 我用官方固件插闪迪的64G进行扩容没问题
