### ISSUE TITLE
两个zip的包文件很多，具体的使用方式

### ISSUE THREAD

**Issue by ukiyoec** [xmapst/GL-MT1300_Plugin#7]
您好请问下载的两个zip的包文件很多，具体的使用方式可以指导一下吗。。不能一个一个安装把。。。

**Comment by xmapst** [comment]
> 您好请问下载的两个zip的包文件很多，具体的使用方式可以指导一下吗。。不能一个一个安装把。。。

有安装脚本在压缩版包内的
